<?php

namespace OC\UserBundle\Repository;

/**
 * CrenoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrenoRepository extends \Doctrine\ORM\EntityRepository
{
}
