<?php

namespace OC\UserBundle\Repository;

/**
 * EcheanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcheanceRepository extends \Doctrine\ORM\EntityRepository {
    
}
