<?php

namespace OC\UserBundle\Repository;

/**
 * LivredorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivredorRepository extends \Doctrine\ORM\EntityRepository
{
}
