<?php

namespace OC\UserBundle\Repository;

/**
 * MatchhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchhRepository extends \Doctrine\ORM\EntityRepository {
    
}
