<?php

namespace OC\UserBundle\Repository;

/**
 * MessagerieexterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagerieexterneRepository extends \Doctrine\ORM\EntityRepository
{
}
