<?php

namespace OC\UserBundle\Repository;

/**
 * MessagerieinterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagerieinterneRepository extends \Doctrine\ORM\EntityRepository
{
}
