parameters:
   database_host: localhost
   database_port: null
   database_name: hostinger_moueza_symfony
   database_user: root
   database_password: hem7pton
   mailer_transport: smtp
   mailer_host: 127.0.0.1
   mailer_user: null
   mailer_password: null
   secret: 1d9ee31768e365a7ed865e7a0246e07a7f6e2935
   secret: 68668603
