parameters:
    database_host: sql205.byethost5.com
    database_port: null
    database_name: b5_19199053_moi
    database_user: b5_19199053
    database_password: pitza5
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 1d9ee31768e365a7ed865e7a0246e07a7f6e2935

