<?php

namespace Proxies\__CG__\OC\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Echeance extends \OC\UserBundle\Entity\Echeance implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'to', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'from', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'id', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'date', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'number', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'deltaDays'];
        }

        return ['__isInitialized__', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'to', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'from', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'id', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'date', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'number', '' . "\0" . 'OC\\UserBundle\\Entity\\Echeance' . "\0" . 'deltaDays'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Echeance $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDates($date1, $date2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDates', [$date1, $date2]);

        return parent::setDates($date1, $date2);
    }

    /**
     * {@inheritDoc}
     */
    public function numberecheancesToDate4N($nthEcheanc, $nbIntervals, $date1, $date2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'numberecheancesToDate4N', [$nthEcheanc, $nbIntervals, $date1, $date2]);

        return parent::numberecheancesToDate4N($nthEcheanc, $nbIntervals, $date1, $date2);
    }

    /**
     * {@inheritDoc}
     */
    public function numberecheancesToDate3N($numberEcheanc, $nbInscritss, $n)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'numberecheancesToDate3N', [$numberEcheanc, $nbInscritss, $n]);

        return parent::numberecheancesToDate3N($numberEcheanc, $nbInscritss, $n);
    }

    /**
     * {@inheritDoc}
     */
    public function echeancesinscritsmoinsunToDatesPERIOD($echeancesNbinscritsmoinsun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'echeancesinscritsmoinsunToDatesPERIOD', [$echeancesNbinscritsmoinsun]);

        return parent::echeancesinscritsmoinsunToDatesPERIOD($echeancesNbinscritsmoinsun);
    }

    /**
     * {@inheritDoc}
     */
    public function nthecheanceNbintervalsToDate($noEcheance, $echeancesNbinscritsmoinsun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nthecheanceNbintervalsToDate', [$noEcheance, $echeancesNbinscritsmoinsun]);

        return parent::nthecheanceNbintervalsToDate($noEcheance, $echeancesNbinscritsmoinsun);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeltaDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeltaDays', []);

        return parent::setDeltaDays();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeltaDays2($date1, $date2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeltaDays2', [$date1, $date2]);

        return parent::getDeltaDays2($date1, $date2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeltaDays0()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeltaDays0', []);

        return parent::getDeltaDays0();
    }

    /**
     * {@inheritDoc}
     */
    public function present2echeance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'present2echeance', []);

        return parent::present2echeance();
    }

    /**
     * {@inheritDoc}
     */
    public function setTo($to)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTo', [$to]);

        return parent::setTo($to);
    }

    /**
     * {@inheritDoc}
     */
    public function getTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTo', []);

        return parent::getTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrom($from)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrom', [$from]);

        return parent::setFrom($from);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrom', []);

        return parent::getFrom();
    }

}
