<?php

namespace Proxies\__CG__\OC\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inscrit extends \OC\UserBundle\Entity\Inscrit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'id', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'date', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'email', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'password', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'isPseudoOVS', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'is_rulesAccepted', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'is_femme', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'roles', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'salt', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'username'];
        }

        return ['__isInitialized__', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'id', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'date', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'email', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'password', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'isPseudoOVS', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'is_rulesAccepted', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'is_femme', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'roles', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'salt', '' . "\0" . 'OC\\UserBundle\\Entity\\Inscrit' . "\0" . 'username'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inscrit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueur1mail($joueur1mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueur1mail', [$joueur1mail]);

        return parent::setJoueur1mail($joueur1mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueur1mail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueur1mail', []);

        return parent::getJoueur1mail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPseudoOVS($isPseudoOVS)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPseudoOVS', [$isPseudoOVS]);

        return parent::setIsPseudoOVS($isPseudoOVS);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPseudoOVS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPseudoOVS', []);

        return parent::getIsPseudoOVS();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRulesAccepted($isRulesAccepted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRulesAccepted', [$isRulesAccepted]);

        return parent::setIsRulesAccepted($isRulesAccepted);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRulesAccepted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRulesAccepted', []);

        return parent::getIsRulesAccepted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFemme($isFemme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFemme', [$isFemme]);

        return parent::setIsFemme($isFemme);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFemme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFemme', []);

        return parent::getIsFemme();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', [$pseudo]);

        return parent::setPseudo($pseudo);
    }

}
