<?php

namespace Proxies\__CG__\OC\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matchh extends \OC\UserBundle\Entity\Matchh implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'id', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'emailone', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'emailtwo', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'creationDatetime', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'beginningDate', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'beginningTime', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'endTime', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score1j1', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score1j2', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'isScore1tie', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'secret', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score2jtournoiNo', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score2j1', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score2j2', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'isScore2tie', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score3j1', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score3j2', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'isScore3tie'];
        }

        return ['__isInitialized__', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'id', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'emailone', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'emailtwo', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'creationDatetime', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'beginningDate', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'beginningTime', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'endTime', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score1j1', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score1j2', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'isScore1tie', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'secret', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score2jtournoiNo', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score2j1', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score2j2', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'isScore2tie', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score3j1', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'score3j2', '' . "\0" . 'OC\\UserBundle\\Entity\\Matchh' . "\0" . 'isScore3tie'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matchh $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDatetime($creationDatetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDatetime', [$creationDatetime]);

        return parent::setCreationDatetime($creationDatetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDatetime', []);

        return parent::getCreationDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeginningDate($beginningDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeginningDate', [$beginningDate]);

        return parent::setBeginningDate($beginningDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeginningDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeginningDate', []);

        return parent::getBeginningDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeginningTime($beginningTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeginningTime', [$beginningTime]);

        return parent::setBeginningTime($beginningTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeginningTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeginningTime', []);

        return parent::getBeginningTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndTime($endTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndTime', [$endTime]);

        return parent::setEndTime($endTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndTime', []);

        return parent::getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore1j1($score1j1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore1j1', [$score1j1]);

        return parent::setScore1j1($score1j1);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore1j1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore1j1', []);

        return parent::getScore1j1();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore1j2($score1j2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore1j2', [$score1j2]);

        return parent::setScore1j2($score1j2);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore1j2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore1j2', []);

        return parent::getScore1j2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsScore1tie($isScore1tie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsScore1tie', [$isScore1tie]);

        return parent::setIsScore1tie($isScore1tie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsScore1tie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsScore1tie', []);

        return parent::getIsScore1tie();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore2j1($score2j1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore2j1', [$score2j1]);

        return parent::setScore2j1($score2j1);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore2j1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore2j1', []);

        return parent::getScore2j1();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore2j2($score2j2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore2j2', [$score2j2]);

        return parent::setScore2j2($score2j2);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore2j2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore2j2', []);

        return parent::getScore2j2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsScore2tie($isScore2tie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsScore2tie', [$isScore2tie]);

        return parent::setIsScore2tie($isScore2tie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsScore2tie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsScore2tie', []);

        return parent::getIsScore2tie();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore3j1($score3j1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore3j1', [$score3j1]);

        return parent::setScore3j1($score3j1);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore3j1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore3j1', []);

        return parent::getScore3j1();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore3j2($score3j2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore3j2', [$score3j2]);

        return parent::setScore3j2($score3j2);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore3j2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore3j2', []);

        return parent::getScore3j2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsScore3tie($isScore3tie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsScore3tie', [$isScore3tie]);

        return parent::setIsScore3tie($isScore3tie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsScore3tie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsScore3tie', []);

        return parent::getIsScore3tie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailone(\OC\UserBundle\Entity\Inscrit $emailone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailone', [$emailone]);

        return parent::setEmailone($emailone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailone', []);

        return parent::getEmailone();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmailone(\OC\UserBundle\Entity\Inscrit $emailone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmailone', [$emailone]);

        return parent::addEmailone($emailone);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmailone(\OC\UserBundle\Entity\Inscrit $emailone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmailone', [$emailone]);

        return parent::removeEmailone($emailone);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailtwo($emailtwo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailtwo', [$emailtwo]);

        return parent::setEmailtwo($emailtwo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailtwo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailtwo', []);

        return parent::getEmailtwo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecret($secret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecret', [$secret]);

        return parent::setSecret($secret);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecret', []);

        return parent::getSecret();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore2jtournoiNo($score2jtournoiNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore2jtournoiNo', [$score2jtournoiNo]);

        return parent::setScore2jtournoiNo($score2jtournoiNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore2jtournoiNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore2jtournoiNo', []);

        return parent::getScore2jtournoiNo();
    }

}
